/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Anthony Yanez (https://sketchfab.com/paulyanez)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/animated-donkey-kong-original-c9e2d5ca47644ce298a56cd524059b2d
title: Animated Donkey Kong (Original)
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import model from "./animated_donkey_kong_original.glb"

export function AnimatedDK(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    model
  );
  const { actions, names } = useAnimations(animations, group);

  useEffect(() => {
    actions[names[0]].startAt(3).play();
  }, [actions,names]);

  return (
    <group scale={0.004} ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group
            name="9b5f004d3d06486e80996c0b46ff9932fbx"
            rotation={[Math.PI / 2, 0, 0]}
          >
            <group name="Object_2">
              <group name="RootNode">
                <group
                  name="Body"
                  position={[-1.21, 54.42, 0]}
                  scale={[1, 1, 1.75]}
                >
                  <group name="Left_Arm" rotation={[0, 0, 0.03]}>
                    <group name="Object_11" position={[0, 42.12, 0]}>
                      <mesh
                        name="Left_Arm_02_-_Default_0"
                        castShadow
                        receiveShadow
                        geometry={nodes["Left_Arm_02_-_Default_0"].geometry}
                        material={materials["02_-_Default"]}
                      />
                      <mesh
                        name="Left_Arm_07_-_Default_0"
                        castShadow
                        receiveShadow
                        geometry={nodes["Left_Arm_07_-_Default_0"].geometry}
                        material={materials["07_-_Default"]}
                      />
                      <mesh
                        name="Left_Arm_03_-_Default_0"
                        castShadow
                        receiveShadow
                        geometry={nodes["Left_Arm_03_-_Default_0"].geometry}
                        material={materials["03_-_Default"]}
                      />
                    </group>
                  </group>
                  <group name="Right_Arm">
                    <group name="Object_16" position={[0, 42.12, 0]}>
                      <mesh
                        name="Right_Arm_02_-_Default_0"
                        castShadow
                        receiveShadow
                        geometry={nodes["Right_Arm_02_-_Default_0"].geometry}
                        material={materials["02_-_Default"]}
                      />
                      <mesh
                        name="Right_Arm_07_-_Default_0"
                        castShadow
                        receiveShadow
                        geometry={nodes["Right_Arm_07_-_Default_0"].geometry}
                        material={materials["07_-_Default"]}
                      />
                      <mesh
                        name="Right_Arm_03_-_Default_0"
                        castShadow
                        receiveShadow
                        geometry={nodes["Right_Arm_03_-_Default_0"].geometry}
                        material={materials["03_-_Default"]}
                      />
                    </group>
                  </group>
                  <group name="Right_Leg">
                    <group name="Object_21" position={[0, 42.12, 0]}>
                      <mesh
                        name="Right_Leg_02_-_Default_0"
                        castShadow
                        receiveShadow
                        geometry={nodes["Right_Leg_02_-_Default_0"].geometry}
                        material={materials["02_-_Default"]}
                      />
                      <mesh
                        name="Right_Leg_03_-_Default_0"
                        castShadow
                        receiveShadow
                        geometry={nodes["Right_Leg_03_-_Default_0"].geometry}
                        material={materials["03_-_Default"]}
                      />
                      <mesh
                        name="Right_Leg_07_-_Default_0"
                        castShadow
                        receiveShadow
                        geometry={nodes["Right_Leg_07_-_Default_0"].geometry}
                        material={materials["07_-_Default"]}
                      />
                    </group>
                  </group>
                  <group name="Left_Hand">
                    <group name="Object_26" position={[0, 42.12, 0]}>
                      <mesh
                        name="Left_Hand_02_-_Default_0"
                        castShadow
                        receiveShadow
                        geometry={nodes["Left_Hand_02_-_Default_0"].geometry}
                        material={materials["02_-_Default"]}
                      />
                      <mesh
                        name="Left_Hand_03_-_Default_0"
                        castShadow
                        receiveShadow
                        geometry={nodes["Left_Hand_03_-_Default_0"].geometry}
                        material={materials["03_-_Default"]}
                      />
                      <mesh
                        name="Left_Hand_07_-_Default_0"
                        castShadow
                        receiveShadow
                        geometry={nodes["Left_Hand_07_-_Default_0"].geometry}
                        material={materials["07_-_Default"]}
                      />
                    </group>
                  </group>
                  <group name="Object_5" position={[0, 42.12, 0]}>
                    <mesh
                      name="Body_03_-_Default_0"
                      castShadow
                      receiveShadow
                      geometry={nodes["Body_03_-_Default_0"].geometry}
                      material={materials["03_-_Default"]}
                    />
                    <mesh
                      name="Body_02_-_Default_0"
                      castShadow
                      receiveShadow
                      geometry={nodes["Body_02_-_Default_0"].geometry}
                      material={materials["02_-_Default"]}
                    />
                    <mesh
                      name="Body_08_-_Default_0"
                      castShadow
                      receiveShadow
                      geometry={nodes["Body_08_-_Default_0"].geometry}
                      material={materials["08_-_Default"]}
                    />
                    <mesh
                      name="Body_09_-_Default_0"
                      castShadow
                      receiveShadow
                      geometry={nodes["Body_09_-_Default_0"].geometry}
                      material={materials["09_-_Default"]}
                    />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/animated_donkey_kong_original.glb");
