/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: ARCTIC  WOLVES™ (https://sketchfab.com/arctic.wolves)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/letter-for-santa-bcd4e00de2944401bc164b8e7859b6e9
title: Letter for Santa
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import model from "./letter_for_santa.glb"

export function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(model);
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group
          name="Sketchfab_model"
          position={[0, -0.1, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.14}
        >
          <group name="SantaMailsFBX" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="SantaMail">
                  <group name="Object_5">
                    <primitive object={nodes._rootJoint} />
                    <group
                      name="Object_7"
                      position={[-0.6, -0.01, -0.4]}
                      rotation={[-Math.PI / 2, 0, 0]}
                    />
                    <group name="SantaMails_mesh" />
                    <skinnedMesh
                      name="Object_8"
                      geometry={nodes.Object_8.geometry}
                      material={materials.Material_27}
                      skeleton={nodes.Object_8.skeleton}
                    />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/letter_for_santa.glb");
