/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Studio.5 (https://sketchfab.com/YogoshimoMoritz)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/santa-scene-3december-b663b72039cc4ff6875ef9ad7879e143
title: Santa Scene - 3December
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import model from "./santa_scene_-_3december.glb";

export function SantaScene(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    model
  );
  const { actions, names } = useAnimations(animations, group);

  useEffect(() => {
    actions[names[0]].startAt(3).play();
  }, [actions,names]);

  return (
    <group scale={0.003} position={[0,-0.2,0]} ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group
            name="32db913f49fe45c29261d08adf3b9a10fbx"
            rotation={[Math.PI / 2, 0, 0]}
          >
            <group name="Object_2">
              <group name="RootNode">
                <group name="Santa_Scene">
                  <group
                    name="Waving__2____Santa"
                    position={[0, 21.8, 0]}
                    rotation={[0, 0.26, 0]}
                    scale={3}
                  >
                    <group name="Object_6">
                      <primitive object={nodes._rootJoint} />
                      <group
                        name="Object_8"
                        position={[0, 21.8, 0]}
                        rotation={[0, 0.26, 0]}
                        scale={3}
                      />
                      <group name="Poly_Santa" />
                      <skinnedMesh
                        name="Object_9"
                        geometry={nodes.Object_9.geometry}
                        material={materials.Poly_Santa___00}
                        skeleton={nodes.Object_9.skeleton}
                      />
                    </group>
                  </group>
                  <group
                    name="DustMotesEffect"
                    position={[0, 319, 0]}
                    rotation={[-Math.PI / 2, 0, -Math.PI / 4]}
                    scale={0.6}
                  />
                  <group
                    name="Gift_s____00_0"
                    position={[-135.9, 21.2, 118]}
                    rotation={[Math.PI, -1.13, -Math.PI]}
                    scale={0.05}
                  >
                    <group name="Gift_s____00_0_1">
                      <mesh
                        name="Gift_s____00_0_1_Gift_s____00_0_0"
                        castShadow
                        receiveShadow
                        geometry={
                          nodes.Gift_s____00_0_1_Gift_s____00_0_0.geometry
                        }
                        material={materials.Gift_s____00_0}
                      />
                    </group>
                  </group>
                  <group
                    name="Gift_s____00_3"
                    position={[63, 23, -58]}
                    rotation={[0, -1.13, 0]}
                    scale={0.04}
                  >
                    <group name="Gift_s____00_3_1">
                      <mesh
                        name="Gift_s____00_3_1_Gift_s____00_0_0"
                        castShadow
                        receiveShadow
                        geometry={
                          nodes.Gift_s____00_3_1_Gift_s____00_0_0.geometry
                        }
                        material={materials.Gift_s____00_0}
                      />
                    </group>
                  </group>
                  <group
                    name="Gift_s____00_1"
                    position={[-112.1, 18, 30.3]}
                    scale={0.08}
                  >
                    <group name="Gift_s____00_1_1">
                      <mesh
                        name="Gift_s____00_1_1_Gift_s____00_0_0"
                        castShadow
                        receiveShadow
                        geometry={
                          nodes.Gift_s____00_1_1_Gift_s____00_0_0.geometry
                        }
                        material={materials.Gift_s____00_0}
                      />
                    </group>
                  </group>
                  <group
                    name="Gift_s____00_2"
                    position={[109, 21.1, 0]}
                    scale={0.06}
                  >
                    <group name="Gift_s____00_2_1">
                      <mesh
                        name="Gift_s____00_2_1_Gift_s____00_0_0"
                        castShadow
                        receiveShadow
                        geometry={
                          nodes.Gift_s____00_2_1_Gift_s____00_0_0.geometry
                        }
                        material={materials.Gift_s____00_0}
                      />
                    </group>
                  </group>
                  <group
                    name="Gift_s____00_2__1_"
                    position={[-195.7, 21.1, 0]}
                    scale={0.06}
                  >
                    <group name="Gift_s____00_2_2">
                      <mesh
                        name="Gift_s____00_2_2_Gift_s____00_0_0"
                        castShadow
                        receiveShadow
                        geometry={
                          nodes.Gift_s____00_2_2_Gift_s____00_0_0.geometry
                        }
                        material={materials.Gift_s____00_0}
                      />
                    </group>
                  </group>
                  <group
                    name="Gift_s____00_0__1_"
                    position={[-73.3, 21.2, -68]}
                    rotation={[Math.PI, -1.13, -Math.PI]}
                    scale={0.05}
                  >
                    <group name="Gift_s____00_0_2">
                      <mesh
                        name="Gift_s____00_0_2_Gift_s____00_0_0"
                        castShadow
                        receiveShadow
                        geometry={
                          nodes.Gift_s____00_0_2_Gift_s____00_0_0.geometry
                        }
                        material={materials.Gift_s____00_0}
                      />
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/santa_scene_-_3december.glb");
