/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Tycho Magnetic Anomaly (https://sketchfab.com/Tycho_Magnetic_Anomaly)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/spectral-circles-028b5706672b44b8bbe399dd19118a50
title: Spectral Circles
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import model from "./spectral_circles.glb";

export function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(model);
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Sphere_0" position={[0, 0.99, -1]}>
                <mesh
                  name="Object_4"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_4.geometry}
                  material={materials.material}
                />
              </group>
              <group name="Cube_1" scale={0.2}>
                <mesh
                  name="Object_6"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_6.geometry}
                  material={materials.hide}
                />
              </group>
              <group name="Sphere001_2" position={[-0.17, 1, -0.98]}>
                <mesh
                  name="Object_8"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_8.geometry}
                  material={materials.material}
                />
              </group>
              <group name="Cube002_3" scale={0.2}>
                <mesh
                  name="Object_10"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_10.geometry}
                  material={materials.hide}
                />
              </group>
              <group name="Sphere002_4" position={[-0.34, 1, -0.94]}>
                <mesh
                  name="Object_12"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_12.geometry}
                  material={materials.material}
                />
              </group>
              <group name="Cube004_5" scale={0.2}>
                <mesh
                  name="Object_14"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_14.geometry}
                  material={materials.hide}
                />
              </group>
              <group name="Sphere003_6" position={[-0.5, 1, -0.87]}>
                <mesh
                  name="Object_16"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_16.geometry}
                  material={materials.material}
                />
              </group>
              <group name="Cube006_7" scale={0.2}>
                <mesh
                  name="Object_18"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_18.geometry}
                  material={materials.hide}
                />
              </group>
              <group name="Sphere004_8" position={[-0.64, 1, -0.77]}>
                <mesh
                  name="Object_20"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_20.geometry}
                  material={materials.material}
                />
              </group>
              <group name="Cube008_9" scale={0.2}>
                <mesh
                  name="Object_22"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_22.geometry}
                  material={materials.hide}
                />
              </group>
              <group name="Sphere005_10" position={[-0.77, 1, -0.64]}>
                <mesh
                  name="Object_24"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_24.geometry}
                  material={materials.material}
                />
              </group>
              <group name="Cube010_11" scale={0.2}>
                <mesh
                  name="Object_26"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_26.geometry}
                  material={materials.hide}
                />
              </group>
              <group name="Sphere006_12" position={[-0.87, 1, -0.5]}>
                <mesh
                  name="Object_28"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_28.geometry}
                  material={materials.material}
                />
              </group>
              <group name="Cube012_13" scale={0.2}>
                <mesh
                  name="Object_30"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_30.geometry}
                  material={materials.hide}
                />
              </group>
              <group name="Sphere007_14" position={[-0.94, 1, -0.34]}>
                <mesh
                  name="Object_32"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_32.geometry}
                  material={materials.material}
                />
              </group>
              <group name="Cube014_15" scale={0.2}>
                <mesh
                  name="Object_34"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_34.geometry}
                  material={materials.hide}
                />
              </group>
              <group name="Sphere008_16" position={[-0.98, 1, -0.17]}>
                <mesh
                  name="Object_36"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_36.geometry}
                  material={materials.material}
                />
              </group>
              <group name="Cube016_17" scale={0.2}>
                <mesh
                  name="Object_38"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_38.geometry}
                  material={materials.hide}
                />
              </group>
              <group name="Sphere009_18" position={[-1, 1, 0]}>
                <mesh
                  name="Object_40"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_40.geometry}
                  material={materials.material}
                />
              </group>
              <group name="Cube018_19" scale={0.2}>
                <mesh
                  name="Object_42"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_42.geometry}
                  material={materials.hide}
                />
              </group>
              <group name="Sphere010_20" position={[-0.98, 1, 0.17]}>
                <mesh
                  name="Object_44"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_44.geometry}
                  material={materials.material}
                />
              </group>
              <group name="Cube020_21" scale={0.2}>
                <mesh
                  name="Object_46"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_46.geometry}
                  material={materials.hide}
                />
              </group>
              <group name="Sphere011_22" position={[-0.94, 1, 0.34]}>
                <mesh
                  name="Object_48"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_48.geometry}
                  material={materials.material}
                />
              </group>
              <group name="Cube022_23" scale={0.2}>
                <mesh
                  name="Object_50"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_50.geometry}
                  material={materials.hide}
                />
              </group>
              <group name="Sphere012_24" position={[-0.87, 1, 0.5]}>
                <mesh
                  name="Object_52"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_52.geometry}
                  material={materials.material}
                />
              </group>
              <group name="Cube024_25" scale={0.2}>
                <mesh
                  name="Object_54"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_54.geometry}
                  material={materials.hide}
                />
              </group>
              <group name="Sphere013_26" position={[-0.77, 1, 0.64]}>
                <mesh
                  name="Object_56"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_56.geometry}
                  material={materials.material}
                />
              </group>
              <group name="Cube026_27" scale={0.2}>
                <mesh
                  name="Object_58"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_58.geometry}
                  material={materials.hide}
                />
              </group>
              <group name="Sphere014_28" position={[-0.64, 1, 0.77]}>
                <mesh
                  name="Object_60"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_60.geometry}
                  material={materials.material}
                />
              </group>
              <group name="Cube028_29" scale={0.2}>
                <mesh
                  name="Object_62"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_62.geometry}
                  material={materials.hide}
                />
              </group>
              <group name="Sphere015_30" position={[-0.5, 1, 0.87]}>
                <mesh
                  name="Object_64"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_64.geometry}
                  material={materials.material}
                />
              </group>
              <group name="Cube030_31" scale={0.2}>
                <mesh
                  name="Object_66"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_66.geometry}
                  material={materials.hide}
                />
              </group>
              <group name="Sphere016_32" position={[-0.34, 1, 0.94]}>
                <mesh
                  name="Object_68"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_68.geometry}
                  material={materials.material}
                />
              </group>
              <group name="Cube032_33" scale={0.2}>
                <mesh
                  name="Object_70"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_70.geometry}
                  material={materials.hide}
                />
              </group>
              <group name="Sphere017_34" position={[-0.17, 1, 0.98]}>
                <mesh
                  name="Object_72"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_72.geometry}
                  material={materials.material}
                />
              </group>
              <group name="Cube034_35" scale={0.2}>
                <mesh
                  name="Object_74"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_74.geometry}
                  material={materials.hide}
                />
              </group>
              <group name="Sphere018_36" position={[0, 1, 1]}>
                <mesh
                  name="Object_76"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_76.geometry}
                  material={materials.material}
                />
              </group>
              <group name="Cube036_37" scale={0.2}>
                <mesh
                  name="Object_78"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_78.geometry}
                  material={materials.hide}
                />
              </group>
              <group name="Sphere019_38" position={[0.17, 1, 0.98]}>
                <mesh
                  name="Object_80"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_80.geometry}
                  material={materials.material}
                />
              </group>
              <group name="Cube038_39" scale={0.2}>
                <mesh
                  name="Object_82"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_82.geometry}
                  material={materials.hide}
                />
              </group>
              <group name="Sphere020_40" position={[0.34, 1, 0.94]}>
                <mesh
                  name="Object_84"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_84.geometry}
                  material={materials.material}
                />
              </group>
              <group name="Cube040_41" scale={0.2}>
                <mesh
                  name="Object_86"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_86.geometry}
                  material={materials.hide}
                />
              </group>
              <group name="Sphere021_42" position={[0.5, 1, 0.87]}>
                <mesh
                  name="Object_88"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_88.geometry}
                  material={materials.material}
                />
              </group>
              <group name="Cube042_43" scale={0.2}>
                <mesh
                  name="Object_90"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_90.geometry}
                  material={materials.hide}
                />
              </group>
              <group name="Sphere022_44" position={[0.64, 1, 0.77]}>
                <mesh
                  name="Object_92"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_92.geometry}
                  material={materials.material}
                />
              </group>
              <group name="Cube044_45" scale={0.2}>
                <mesh
                  name="Object_94"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_94.geometry}
                  material={materials.hide}
                />
              </group>
              <group name="Sphere023_46" position={[0.77, 1, 0.64]}>
                <mesh
                  name="Object_96"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_96.geometry}
                  material={materials.material}
                />
              </group>
              <group name="Cube046_47" scale={0.2}>
                <mesh
                  name="Object_98"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_98.geometry}
                  material={materials.hide}
                />
              </group>
              <group name="Sphere024_48" position={[0.87, 1, 0.5]}>
                <mesh
                  name="Object_100"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_100.geometry}
                  material={materials.material}
                />
              </group>
              <group name="Cube048_49" scale={0.2}>
                <mesh
                  name="Object_102"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_102.geometry}
                  material={materials.hide}
                />
              </group>
              <group name="Sphere025_50" position={[0.94, 1, 0.34]}>
                <mesh
                  name="Object_104"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_104.geometry}
                  material={materials.material}
                />
              </group>
              <group name="Cube050_51" scale={0.2}>
                <mesh
                  name="Object_106"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_106.geometry}
                  material={materials.hide}
                />
              </group>
              <group name="Sphere026_52" position={[0.98, 1, 0.17]}>
                <mesh
                  name="Object_108"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_108.geometry}
                  material={materials.material}
                />
              </group>
              <group name="Cube052_53" scale={0.2}>
                <mesh
                  name="Object_110"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_110.geometry}
                  material={materials.hide}
                />
              </group>
              <group name="Sphere027_54" position={[1, 1, 0]}>
                <mesh
                  name="Object_112"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_112.geometry}
                  material={materials.material}
                />
              </group>
              <group name="Cube054_55" scale={0.2}>
                <mesh
                  name="Object_114"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_114.geometry}
                  material={materials.hide}
                />
              </group>
              <group name="Sphere028_56" position={[0.98, 1, -0.17]}>
                <mesh
                  name="Object_116"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_116.geometry}
                  material={materials.material}
                />
              </group>
              <group name="Cube056_57" scale={0.2}>
                <mesh
                  name="Object_118"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_118.geometry}
                  material={materials.hide}
                />
              </group>
              <group name="Sphere029_58" position={[0.94, 1, -0.34]}>
                <mesh
                  name="Object_120"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_120.geometry}
                  material={materials.material}
                />
              </group>
              <group name="Cube058_59" scale={0.2}>
                <mesh
                  name="Object_122"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_122.geometry}
                  material={materials.hide}
                />
              </group>
              <group name="Sphere030_60" position={[0.87, 1, -0.5]}>
                <mesh
                  name="Object_124"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_124.geometry}
                  material={materials.material}
                />
              </group>
              <group name="Cube060_61" scale={0.2}>
                <mesh
                  name="Object_126"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_126.geometry}
                  material={materials.hide}
                />
              </group>
              <group name="Sphere031_62" position={[0.77, 1, -0.64]}>
                <mesh
                  name="Object_128"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_128.geometry}
                  material={materials.material}
                />
              </group>
              <group name="Cube062_63" scale={0.2}>
                <mesh
                  name="Object_130"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_130.geometry}
                  material={materials.hide}
                />
              </group>
              <group name="Sphere032_64" position={[0.64, 1, -0.77]}>
                <mesh
                  name="Object_132"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_132.geometry}
                  material={materials.material}
                />
              </group>
              <group name="Cube064_65" scale={0.2}>
                <mesh
                  name="Object_134"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_134.geometry}
                  material={materials.hide}
                />
              </group>
              <group name="Sphere033_66" position={[0.5, 1, -0.87]}>
                <mesh
                  name="Object_136"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_136.geometry}
                  material={materials.material}
                />
              </group>
              <group name="Cube066_67" scale={0.2}>
                <mesh
                  name="Object_138"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_138.geometry}
                  material={materials.hide}
                />
              </group>
              <group name="Sphere034_68" position={[0.34, 1, -0.94]}>
                <mesh
                  name="Object_140"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_140.geometry}
                  material={materials.material}
                />
              </group>
              <group name="Cube068_69" scale={0.2}>
                <mesh
                  name="Object_142"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_142.geometry}
                  material={materials.hide}
                />
              </group>
              <group name="Sphere035_70" position={[0.17, 1, -0.98]}>
                <mesh
                  name="Object_144"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_144.geometry}
                  material={materials.material}
                />
              </group>
              <group name="Cube070_71" scale={0.2}>
                <mesh
                  name="Object_146"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_146.geometry}
                  material={materials.hide}
                />
              </group>
              <group
                name="Sphere036_110"
                position={[0.14, 0.59, -0.79]}
                scale={0.8}
              >
                <mesh
                  name="Object_224"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_224.geometry}
                  material={materials.material_3}
                />
              </group>
              <group name="Cube073_111" position={[0, -0.2, 0]} scale={0.16}>
                <mesh
                  name="Object_226"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_226.geometry}
                  material={materials.hide}
                />
              </group>
              <group name="Sphere037_112" position={[0, 0.6, -0.8]} scale={0.8}>
                <mesh
                  name="Object_228"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_228.geometry}
                  material={materials.material_3}
                />
              </group>
              <group name="Cube075_113" position={[0, -0.2, 0]} scale={0.16}>
                <mesh
                  name="Object_230"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_230.geometry}
                  material={materials.hide}
                />
              </group>
              <group
                name="Sphere038_114"
                position={[-0.14, 0.6, -0.79]}
                scale={0.8}
              >
                <mesh
                  name="Object_232"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_232.geometry}
                  material={materials.material_3}
                />
              </group>
              <group name="Cube077_115" position={[0, -0.2, 0]} scale={0.16}>
                <mesh
                  name="Object_234"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_234.geometry}
                  material={materials.hide}
                />
              </group>
              <group
                name="Sphere039_116"
                position={[-0.27, 0.6, -0.75]}
                scale={0.8}
              >
                <mesh
                  name="Object_236"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_236.geometry}
                  material={materials.material_3}
                />
              </group>
              <group name="Cube079_117" position={[0, -0.2, 0]} scale={0.16}>
                <mesh
                  name="Object_238"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_238.geometry}
                  material={materials.hide}
                />
              </group>
              <group
                name="Sphere040_118"
                position={[-0.4, 0.6, -0.69]}
                scale={0.8}
              >
                <mesh
                  name="Object_240"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_240.geometry}
                  material={materials.material_3}
                />
              </group>
              <group name="Cube081_119" position={[0, -0.2, 0]} scale={0.16}>
                <mesh
                  name="Object_242"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_242.geometry}
                  material={materials.hide}
                />
              </group>
              <group
                name="Sphere041_120"
                position={[-0.51, 0.6, -0.61]}
                scale={0.8}
              >
                <mesh
                  name="Object_244"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_244.geometry}
                  material={materials.material_3}
                />
              </group>
              <group name="Cube083_121" position={[0, -0.2, 0]} scale={0.16}>
                <mesh
                  name="Object_246"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_246.geometry}
                  material={materials.hide}
                />
              </group>
              <group
                name="Sphere042_122"
                position={[-0.61, 0.6, -0.51]}
                scale={0.8}
              >
                <mesh
                  name="Object_248"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_248.geometry}
                  material={materials.material_3}
                />
              </group>
              <group name="Cube085_123" position={[0, -0.2, 0]} scale={0.16}>
                <mesh
                  name="Object_250"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_250.geometry}
                  material={materials.hide}
                />
              </group>
              <group
                name="Sphere043_124"
                position={[-0.69, 0.6, -0.4]}
                scale={0.8}
              >
                <mesh
                  name="Object_252"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_252.geometry}
                  material={materials.material_3}
                />
              </group>
              <group name="Cube087_125" position={[0, -0.2, 0]} scale={0.16}>
                <mesh
                  name="Object_254"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_254.geometry}
                  material={materials.hide}
                />
              </group>
              <group
                name="Sphere044_126"
                position={[-0.75, 0.6, -0.27]}
                scale={0.8}
              >
                <mesh
                  name="Object_256"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_256.geometry}
                  material={materials.material_3}
                />
              </group>
              <group name="Cube089_127" position={[0, -0.2, 0]} scale={0.16}>
                <mesh
                  name="Object_258"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_258.geometry}
                  material={materials.hide}
                />
              </group>
              <group
                name="Sphere045_128"
                position={[-0.79, 0.6, -0.14]}
                scale={0.8}
              >
                <mesh
                  name="Object_260"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_260.geometry}
                  material={materials.material_3}
                />
              </group>
              <group name="Cube091_129" position={[0, -0.2, 0]} scale={0.16}>
                <mesh
                  name="Object_262"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_262.geometry}
                  material={materials.hide}
                />
              </group>
              <group name="Sphere046_130" position={[-0.8, 0.6, 0]} scale={0.8}>
                <mesh
                  name="Object_264"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_264.geometry}
                  material={materials.material_3}
                />
              </group>
              <group name="Cube093_131" position={[0, -0.2, 0]} scale={0.16}>
                <mesh
                  name="Object_266"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_266.geometry}
                  material={materials.hide}
                />
              </group>
              <group
                name="Sphere047_132"
                position={[-0.79, 0.6, 0.14]}
                scale={0.8}
              >
                <mesh
                  name="Object_268"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_268.geometry}
                  material={materials.material_3}
                />
              </group>
              <group name="Cube095_133" position={[0, -0.2, 0]} scale={0.16}>
                <mesh
                  name="Object_270"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_270.geometry}
                  material={materials.hide}
                />
              </group>
              <group
                name="Sphere048_134"
                position={[-0.75, 0.6, 0.27]}
                scale={0.8}
              >
                <mesh
                  name="Object_272"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_272.geometry}
                  material={materials.material_3}
                />
              </group>
              <group name="Cube097_135" position={[0, -0.2, 0]} scale={0.16}>
                <mesh
                  name="Object_274"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_274.geometry}
                  material={materials.hide}
                />
              </group>
              <group
                name="Sphere049_136"
                position={[-0.69, 0.6, 0.4]}
                scale={0.8}
              >
                <mesh
                  name="Object_276"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_276.geometry}
                  material={materials.material_3}
                />
              </group>
              <group name="Cube099_137" position={[0, -0.2, 0]} scale={0.16}>
                <mesh
                  name="Object_278"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_278.geometry}
                  material={materials.hide}
                />
              </group>
              <group
                name="Sphere050_138"
                position={[-0.61, 0.6, 0.51]}
                scale={0.8}
              >
                <mesh
                  name="Object_280"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_280.geometry}
                  material={materials.material_3}
                />
              </group>
              <group name="Cube101_139" position={[0, -0.2, 0]} scale={0.16}>
                <mesh
                  name="Object_282"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_282.geometry}
                  material={materials.hide}
                />
              </group>
              <group
                name="Sphere051_140"
                position={[-0.51, 0.6, 0.61]}
                scale={0.8}
              >
                <mesh
                  name="Object_284"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_284.geometry}
                  material={materials.material_3}
                />
              </group>
              <group name="Cube103_141" position={[0, -0.2, 0]} scale={0.16}>
                <mesh
                  name="Object_286"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_286.geometry}
                  material={materials.hide}
                />
              </group>
              <group
                name="Sphere052_142"
                position={[-0.4, 0.6, 0.69]}
                scale={0.8}
              >
                <mesh
                  name="Object_288"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_288.geometry}
                  material={materials.material_3}
                />
              </group>
              <group name="Cube105_143" position={[0, -0.2, 0]} scale={0.16}>
                <mesh
                  name="Object_290"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_290.geometry}
                  material={materials.hide}
                />
              </group>
              <group
                name="Sphere053_144"
                position={[-0.27, 0.6, 0.75]}
                scale={0.8}
              >
                <mesh
                  name="Object_292"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_292.geometry}
                  material={materials.material_3}
                />
              </group>
              <group name="Cube107_145" position={[0, -0.2, 0]} scale={0.16}>
                <mesh
                  name="Object_294"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_294.geometry}
                  material={materials.hide}
                />
              </group>
              <group
                name="Sphere054_146"
                position={[-0.14, 0.6, 0.79]}
                scale={0.8}
              >
                <mesh
                  name="Object_296"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_296.geometry}
                  material={materials.material_3}
                />
              </group>
              <group name="Cube109_147" position={[0, -0.2, 0]} scale={0.16}>
                <mesh
                  name="Object_298"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_298.geometry}
                  material={materials.hide}
                />
              </group>
              <group name="Sphere055_148" position={[0, 0.6, 0.8]} scale={0.8}>
                <mesh
                  name="Object_300"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_300.geometry}
                  material={materials.material_3}
                />
              </group>
              <group name="Cube111_149" position={[0, -0.2, 0]} scale={0.16}>
                <mesh
                  name="Object_302"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_302.geometry}
                  material={materials.hide}
                />
              </group>
              <group
                name="Sphere056_150"
                position={[0.14, 0.6, 0.79]}
                scale={0.8}
              >
                <mesh
                  name="Object_304"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_304.geometry}
                  material={materials.material_3}
                />
              </group>
              <group name="Cube113_151" position={[0, -0.2, 0]} scale={0.16}>
                <mesh
                  name="Object_306"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_306.geometry}
                  material={materials.hide}
                />
              </group>
              <group
                name="Sphere057_152"
                position={[0.27, 0.6, 0.75]}
                scale={0.8}
              >
                <mesh
                  name="Object_308"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_308.geometry}
                  material={materials.material_3}
                />
              </group>
              <group name="Cube115_153" position={[0, -0.2, 0]} scale={0.16}>
                <mesh
                  name="Object_310"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_310.geometry}
                  material={materials.hide}
                />
              </group>
              <group
                name="Sphere058_154"
                position={[0.4, 0.6, 0.69]}
                scale={0.8}
              >
                <mesh
                  name="Object_312"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_312.geometry}
                  material={materials.material_3}
                />
              </group>
              <group name="Cube117_155" position={[0, -0.2, 0]} scale={0.16}>
                <mesh
                  name="Object_314"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_314.geometry}
                  material={materials.hide}
                />
              </group>
              <group
                name="Sphere059_156"
                position={[0.51, 0.6, 0.61]}
                scale={0.8}
              >
                <mesh
                  name="Object_316"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_316.geometry}
                  material={materials.material_3}
                />
              </group>
              <group name="Cube119_157" position={[0, -0.2, 0]} scale={0.16}>
                <mesh
                  name="Object_318"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_318.geometry}
                  material={materials.hide}
                />
              </group>
              <group
                name="Sphere060_158"
                position={[0.61, 0.6, 0.51]}
                scale={0.8}
              >
                <mesh
                  name="Object_320"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_320.geometry}
                  material={materials.material_3}
                />
              </group>
              <group name="Cube121_159" position={[0, -0.2, 0]} scale={0.16}>
                <mesh
                  name="Object_322"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_322.geometry}
                  material={materials.hide}
                />
              </group>
              <group
                name="Sphere061_160"
                position={[0.69, 0.6, 0.4]}
                scale={0.8}
              >
                <mesh
                  name="Object_324"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_324.geometry}
                  material={materials.material_3}
                />
              </group>
              <group name="Cube123_161" position={[0, -0.2, 0]} scale={0.16}>
                <mesh
                  name="Object_326"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_326.geometry}
                  material={materials.hide}
                />
              </group>
              <group
                name="Sphere062_162"
                position={[0.75, 0.6, 0.27]}
                scale={0.8}
              >
                <mesh
                  name="Object_328"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_328.geometry}
                  material={materials.material_3}
                />
              </group>
              <group name="Cube125_163" position={[0, -0.2, 0]} scale={0.16}>
                <mesh
                  name="Object_330"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_330.geometry}
                  material={materials.hide}
                />
              </group>
              <group
                name="Sphere063_164"
                position={[0.79, 0.6, 0.14]}
                scale={0.8}
              >
                <mesh
                  name="Object_332"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_332.geometry}
                  material={materials.material_3}
                />
              </group>
              <group name="Cube127_165" position={[0, -0.2, 0]} scale={0.16}>
                <mesh
                  name="Object_334"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_334.geometry}
                  material={materials.hide}
                />
              </group>
              <group name="Sphere064_166" position={[0.8, 0.6, 0]} scale={0.8}>
                <mesh
                  name="Object_336"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_336.geometry}
                  material={materials.material_3}
                />
              </group>
              <group name="Cube129_167" position={[0, -0.2, 0]} scale={0.16}>
                <mesh
                  name="Object_338"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_338.geometry}
                  material={materials.hide}
                />
              </group>
              <group
                name="Sphere065_168"
                position={[0.79, 0.6, -0.14]}
                scale={0.8}
              >
                <mesh
                  name="Object_340"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_340.geometry}
                  material={materials.material_3}
                />
              </group>
              <group name="Cube131_169" position={[0, -0.2, 0]} scale={0.16}>
                <mesh
                  name="Object_342"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_342.geometry}
                  material={materials.hide}
                />
              </group>
              <group
                name="Sphere066_170"
                position={[0.75, 0.6, -0.27]}
                scale={0.8}
              >
                <mesh
                  name="Object_344"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_344.geometry}
                  material={materials.material_3}
                />
              </group>
              <group name="Cube133_171" position={[0, -0.2, 0]} scale={0.16}>
                <mesh
                  name="Object_346"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_346.geometry}
                  material={materials.hide}
                />
              </group>
              <group
                name="Sphere067_172"
                position={[0.69, 0.6, -0.4]}
                scale={0.8}
              >
                <mesh
                  name="Object_348"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_348.geometry}
                  material={materials.material_3}
                />
              </group>
              <group name="Cube135_173" position={[0, -0.2, 0]} scale={0.16}>
                <mesh
                  name="Object_350"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_350.geometry}
                  material={materials.hide}
                />
              </group>
              <group
                name="Sphere068_174"
                position={[0.61, 0.6, -0.51]}
                scale={0.8}
              >
                <mesh
                  name="Object_352"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_352.geometry}
                  material={materials.material_3}
                />
              </group>
              <group name="Cube137_175" position={[0, -0.2, 0]} scale={0.16}>
                <mesh
                  name="Object_354"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_354.geometry}
                  material={materials.hide}
                />
              </group>
              <group
                name="Sphere069_176"
                position={[0.51, 0.6, -0.61]}
                scale={0.8}
              >
                <mesh
                  name="Object_356"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_356.geometry}
                  material={materials.material_3}
                />
              </group>
              <group name="Cube139_177" position={[0, -0.2, 0]} scale={0.16}>
                <mesh
                  name="Object_358"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_358.geometry}
                  material={materials.hide}
                />
              </group>
              <group
                name="Sphere070_178"
                position={[0.4, 0.6, -0.69]}
                scale={0.8}
              >
                <mesh
                  name="Object_360"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_360.geometry}
                  material={materials.material_3}
                />
              </group>
              <group name="Cube141_179" position={[0, -0.2, 0]} scale={0.16}>
                <mesh
                  name="Object_362"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_362.geometry}
                  material={materials.hide}
                />
              </group>
              <group
                name="Sphere071_180"
                position={[0.27, 0.6, -0.75]}
                scale={0.8}
              >
                <mesh
                  name="Object_364"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_364.geometry}
                  material={materials.material_3}
                />
              </group>
              <group name="Cube143_181" position={[0, -0.2, 0]} scale={0.16}>
                <mesh
                  name="Object_366"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_366.geometry}
                  material={materials.hide}
                />
              </group>
              <group name="Cube072_109" scale={1.4}>
                <group name="Cube001_72" scale={0.71}>
                  <mesh
                    name="Object_150"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_150.geometry}
                    material={materials.hide}
                  />
                </group>
                <group name="Cube003_73" rotation={[0, 0.17, 0]} scale={0.71}>
                  <mesh
                    name="Object_152"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_152.geometry}
                    material={materials.hide}
                  />
                </group>
                <group
                  name="Cube005_74"
                  rotation={[0, Math.PI / 9, 0]}
                  scale={0.71}
                >
                  <mesh
                    name="Object_154"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_154.geometry}
                    material={materials.hide}
                  />
                </group>
                <group
                  name="Cube007_75"
                  rotation={[0, Math.PI / 6, 0]}
                  scale={0.71}
                >
                  <mesh
                    name="Object_156"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_156.geometry}
                    material={materials.hide}
                  />
                </group>
                <group name="Cube009_76" rotation={[0, 0.7, 0]} scale={0.71}>
                  <mesh
                    name="Object_158"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_158.geometry}
                    material={materials.hide}
                  />
                </group>
                <group name="Cube011_77" rotation={[0, 0.87, 0]} scale={0.71}>
                  <mesh
                    name="Object_160"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_160.geometry}
                    material={materials.hide}
                  />
                </group>
                <group
                  name="Cube013_78"
                  rotation={[0, Math.PI / 3, 0]}
                  scale={0.71}
                >
                  <mesh
                    name="Object_162"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_162.geometry}
                    material={materials.hide}
                  />
                </group>
                <group name="Cube015_79" rotation={[0, 1.22, 0]} scale={0.71}>
                  <mesh
                    name="Object_164"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_164.geometry}
                    material={materials.hide}
                  />
                </group>
                <group name="Cube017_80" rotation={[0, 1.4, 0]} scale={0.71}>
                  <mesh
                    name="Object_166"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_166.geometry}
                    material={materials.hide}
                  />
                </group>
                <group
                  name="Cube019_81"
                  rotation={[0, Math.PI / 2, 0]}
                  scale={0.71}
                >
                  <mesh
                    name="Object_168"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_168.geometry}
                    material={materials.hide}
                  />
                </group>
                <group
                  name="Cube021_82"
                  rotation={[-Math.PI, 1.4, -Math.PI]}
                  scale={0.71}
                >
                  <mesh
                    name="Object_170"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_170.geometry}
                    material={materials.hide}
                  />
                </group>
                <group
                  name="Cube023_83"
                  rotation={[-Math.PI, 1.22, -Math.PI]}
                  scale={0.71}
                >
                  <mesh
                    name="Object_172"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_172.geometry}
                    material={materials.hide}
                  />
                </group>
                <group
                  name="Cube025_84"
                  rotation={[-Math.PI, Math.PI / 3, -Math.PI]}
                  scale={0.71}
                >
                  <mesh
                    name="Object_174"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_174.geometry}
                    material={materials.hide}
                  />
                </group>
                <group
                  name="Cube027_85"
                  rotation={[-Math.PI, 0.87, -Math.PI]}
                  scale={0.71}
                >
                  <mesh
                    name="Object_176"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_176.geometry}
                    material={materials.hide}
                  />
                </group>
                <group
                  name="Cube029_86"
                  rotation={[-Math.PI, 0.7, -Math.PI]}
                  scale={0.71}
                >
                  <mesh
                    name="Object_178"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_178.geometry}
                    material={materials.hide}
                  />
                </group>
                <group
                  name="Cube031_87"
                  rotation={[-Math.PI, Math.PI / 6, -Math.PI]}
                  scale={0.71}
                >
                  <mesh
                    name="Object_180"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_180.geometry}
                    material={materials.hide}
                  />
                </group>
                <group
                  name="Cube033_88"
                  rotation={[-Math.PI, Math.PI / 9, -Math.PI]}
                  scale={0.71}
                >
                  <mesh
                    name="Object_182"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_182.geometry}
                    material={materials.hide}
                  />
                </group>
                <group
                  name="Cube035_89"
                  rotation={[-Math.PI, 0.17, -Math.PI]}
                  scale={0.71}
                >
                  <mesh
                    name="Object_184"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_184.geometry}
                    material={materials.hide}
                  />
                </group>
                <group
                  name="Cube037_90"
                  rotation={[-Math.PI, 0, -Math.PI]}
                  scale={0.71}
                >
                  <mesh
                    name="Object_186"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_186.geometry}
                    material={materials.hide}
                  />
                </group>
                <group
                  name="Cube039_91"
                  rotation={[-Math.PI, -0.17, -Math.PI]}
                  scale={0.71}
                >
                  <mesh
                    name="Object_188"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_188.geometry}
                    material={materials.hide}
                  />
                </group>
                <group
                  name="Cube041_92"
                  rotation={[-Math.PI, -Math.PI / 9, -Math.PI]}
                  scale={0.71}
                >
                  <mesh
                    name="Object_190"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_190.geometry}
                    material={materials.hide}
                  />
                </group>
                <group
                  name="Cube043_93"
                  rotation={[-Math.PI, -Math.PI / 6, -Math.PI]}
                  scale={0.71}
                >
                  <mesh
                    name="Object_192"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_192.geometry}
                    material={materials.hide}
                  />
                </group>
                <group
                  name="Cube045_94"
                  rotation={[-Math.PI, -0.7, -Math.PI]}
                  scale={0.71}
                >
                  <mesh
                    name="Object_194"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_194.geometry}
                    material={materials.hide}
                  />
                </group>
                <group
                  name="Cube047_95"
                  rotation={[-Math.PI, -0.87, -Math.PI]}
                  scale={0.71}
                >
                  <mesh
                    name="Object_196"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_196.geometry}
                    material={materials.hide}
                  />
                </group>
                <group
                  name="Cube049_96"
                  rotation={[Math.PI, -Math.PI / 3, Math.PI]}
                  scale={0.71}
                >
                  <mesh
                    name="Object_198"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_198.geometry}
                    material={materials.hide}
                  />
                </group>
                <group
                  name="Cube051_97"
                  rotation={[Math.PI, -1.22, Math.PI]}
                  scale={0.71}
                >
                  <mesh
                    name="Object_200"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_200.geometry}
                    material={materials.hide}
                  />
                </group>
                <group
                  name="Cube053_98"
                  rotation={[Math.PI, -1.4, Math.PI]}
                  scale={0.71}
                >
                  <mesh
                    name="Object_202"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_202.geometry}
                    material={materials.hide}
                  />
                </group>
                <group
                  name="Cube055_99"
                  rotation={[0, -Math.PI / 2, 0]}
                  scale={0.71}
                >
                  <mesh
                    name="Object_204"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_204.geometry}
                    material={materials.hide}
                  />
                </group>
                <group name="Cube057_100" rotation={[0, -1.4, 0]} scale={0.71}>
                  <mesh
                    name="Object_206"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_206.geometry}
                    material={materials.hide}
                  />
                </group>
                <group name="Cube059_101" rotation={[0, -1.22, 0]} scale={0.71}>
                  <mesh
                    name="Object_208"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_208.geometry}
                    material={materials.hide}
                  />
                </group>
                <group
                  name="Cube061_102"
                  rotation={[0, -Math.PI / 3, 0]}
                  scale={0.71}
                >
                  <mesh
                    name="Object_210"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_210.geometry}
                    material={materials.hide}
                  />
                </group>
                <group name="Cube063_103" rotation={[0, -0.87, 0]} scale={0.71}>
                  <mesh
                    name="Object_212"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_212.geometry}
                    material={materials.hide}
                  />
                </group>
                <group name="Cube065_104" rotation={[0, -0.7, 0]} scale={0.71}>
                  <mesh
                    name="Object_214"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_214.geometry}
                    material={materials.hide}
                  />
                </group>
                <group
                  name="Cube067_105"
                  rotation={[0, -Math.PI / 6, 0]}
                  scale={0.71}
                >
                  <mesh
                    name="Object_216"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_216.geometry}
                    material={materials.hide}
                  />
                </group>
                <group name="Cube069_106" rotation={[0, -0.35, 0]} scale={0.71}>
                  <mesh
                    name="Object_218"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_218.geometry}
                    material={materials.hide}
                  />
                </group>
                <group name="Cube071_107" rotation={[0, -0.17, 0]} scale={0.71}>
                  <mesh
                    name="Object_220"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_220.geometry}
                    material={materials.hide}
                  />
                </group>
                <group name="Cylinder_108" scale={0.71}>
                  <mesh
                    name="Object_222"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_222.geometry}
                    material={materials.hide}
                  />
                </group>
                <mesh
                  name="Object_148"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_148.geometry}
                  material={materials.material_0}
                />
              </group>
              <group
                name="Cube145_219"
                position={[0, -0.2, 0]}
                rotation={[0, -0.17, 0]}
                scale={1.12}
              >
                <group name="Cube074_182" scale={0.71}>
                  <mesh
                    name="Object_370"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_370.geometry}
                    material={materials.hide}
                  />
                </group>
                <group name="Cube076_183" rotation={[0, 0.17, 0]} scale={0.71}>
                  <mesh
                    name="Object_372"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_372.geometry}
                    material={materials.hide}
                  />
                </group>
                <group
                  name="Cube078_184"
                  rotation={[0, Math.PI / 9, 0]}
                  scale={0.71}
                >
                  <mesh
                    name="Object_374"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_374.geometry}
                    material={materials.hide}
                  />
                </group>
                <group
                  name="Cube080_185"
                  rotation={[0, Math.PI / 6, 0]}
                  scale={0.71}
                >
                  <mesh
                    name="Object_376"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_376.geometry}
                    material={materials.hide}
                  />
                </group>
                <group name="Cube082_186" rotation={[0, 0.7, 0]} scale={0.71}>
                  <mesh
                    name="Object_378"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_378.geometry}
                    material={materials.hide}
                  />
                </group>
                <group name="Cube084_187" rotation={[0, 0.87, 0]} scale={0.71}>
                  <mesh
                    name="Object_380"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_380.geometry}
                    material={materials.hide}
                  />
                </group>
                <group
                  name="Cube086_188"
                  rotation={[0, Math.PI / 3, 0]}
                  scale={0.71}
                >
                  <mesh
                    name="Object_382"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_382.geometry}
                    material={materials.hide}
                  />
                </group>
                <group name="Cube088_189" rotation={[0, 1.22, 0]} scale={0.71}>
                  <mesh
                    name="Object_384"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_384.geometry}
                    material={materials.hide}
                  />
                </group>
                <group name="Cube090_190" rotation={[0, 1.4, 0]} scale={0.71}>
                  <mesh
                    name="Object_386"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_386.geometry}
                    material={materials.hide}
                  />
                </group>
                <group
                  name="Cube092_191"
                  rotation={[0, Math.PI / 2, 0]}
                  scale={0.71}
                >
                  <mesh
                    name="Object_388"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_388.geometry}
                    material={materials.hide}
                  />
                </group>
                <group
                  name="Cube094_192"
                  rotation={[-Math.PI, 1.4, -Math.PI]}
                  scale={0.71}
                >
                  <mesh
                    name="Object_390"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_390.geometry}
                    material={materials.hide}
                  />
                </group>
                <group
                  name="Cube096_193"
                  rotation={[-Math.PI, 1.22, -Math.PI]}
                  scale={0.71}
                >
                  <mesh
                    name="Object_392"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_392.geometry}
                    material={materials.hide}
                  />
                </group>
                <group
                  name="Cube098_194"
                  rotation={[-Math.PI, Math.PI / 3, -Math.PI]}
                  scale={0.71}
                >
                  <mesh
                    name="Object_394"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_394.geometry}
                    material={materials.hide}
                  />
                </group>
                <group
                  name="Cube100_195"
                  rotation={[-Math.PI, 0.87, -Math.PI]}
                  scale={0.71}
                >
                  <mesh
                    name="Object_396"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_396.geometry}
                    material={materials.hide}
                  />
                </group>
                <group
                  name="Cube102_196"
                  rotation={[-Math.PI, 0.7, -Math.PI]}
                  scale={0.71}
                >
                  <mesh
                    name="Object_398"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_398.geometry}
                    material={materials.hide}
                  />
                </group>
                <group
                  name="Cube104_197"
                  rotation={[-Math.PI, Math.PI / 6, -Math.PI]}
                  scale={0.71}
                >
                  <mesh
                    name="Object_400"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_400.geometry}
                    material={materials.hide}
                  />
                </group>
                <group
                  name="Cube106_198"
                  rotation={[-Math.PI, Math.PI / 9, -Math.PI]}
                  scale={0.71}
                >
                  <mesh
                    name="Object_402"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_402.geometry}
                    material={materials.hide}
                  />
                </group>
                <group
                  name="Cube108_199"
                  rotation={[-Math.PI, 0.17, -Math.PI]}
                  scale={0.71}
                >
                  <mesh
                    name="Object_404"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_404.geometry}
                    material={materials.hide}
                  />
                </group>
                <group
                  name="Cube110_200"
                  rotation={[-Math.PI, 0, -Math.PI]}
                  scale={0.71}
                >
                  <mesh
                    name="Object_406"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_406.geometry}
                    material={materials.hide}
                  />
                </group>
                <group
                  name="Cube112_201"
                  rotation={[-Math.PI, -0.17, -Math.PI]}
                  scale={0.71}
                >
                  <mesh
                    name="Object_408"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_408.geometry}
                    material={materials.hide}
                  />
                </group>
                <group
                  name="Cube114_202"
                  rotation={[-Math.PI, -Math.PI / 9, -Math.PI]}
                  scale={0.71}
                >
                  <mesh
                    name="Object_410"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_410.geometry}
                    material={materials.hide}
                  />
                </group>
                <group
                  name="Cube116_203"
                  rotation={[-Math.PI, -Math.PI / 6, -Math.PI]}
                  scale={0.71}
                >
                  <mesh
                    name="Object_412"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_412.geometry}
                    material={materials.hide}
                  />
                </group>
                <group
                  name="Cube118_204"
                  rotation={[-Math.PI, -0.7, -Math.PI]}
                  scale={0.71}
                >
                  <mesh
                    name="Object_414"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_414.geometry}
                    material={materials.hide}
                  />
                </group>
                <group
                  name="Cube120_205"
                  rotation={[-Math.PI, -0.87, -Math.PI]}
                  scale={0.71}
                >
                  <mesh
                    name="Object_416"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_416.geometry}
                    material={materials.hide}
                  />
                </group>
                <group
                  name="Cube122_206"
                  rotation={[Math.PI, -Math.PI / 3, Math.PI]}
                  scale={0.71}
                >
                  <mesh
                    name="Object_418"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_418.geometry}
                    material={materials.hide}
                  />
                </group>
                <group
                  name="Cube124_207"
                  rotation={[Math.PI, -1.22, Math.PI]}
                  scale={0.71}
                >
                  <mesh
                    name="Object_420"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_420.geometry}
                    material={materials.hide}
                  />
                </group>
                <group
                  name="Cube126_208"
                  rotation={[Math.PI, -1.4, Math.PI]}
                  scale={0.71}
                >
                  <mesh
                    name="Object_422"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_422.geometry}
                    material={materials.hide}
                  />
                </group>
                <group
                  name="Cube128_209"
                  rotation={[0, -Math.PI / 2, 0]}
                  scale={0.71}
                >
                  <mesh
                    name="Object_424"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_424.geometry}
                    material={materials.hide}
                  />
                </group>
                <group name="Cube130_210" rotation={[0, -1.4, 0]} scale={0.71}>
                  <mesh
                    name="Object_426"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_426.geometry}
                    material={materials.hide}
                  />
                </group>
                <group name="Cube132_211" rotation={[0, -1.22, 0]} scale={0.71}>
                  <mesh
                    name="Object_428"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_428.geometry}
                    material={materials.hide}
                  />
                </group>
                <group
                  name="Cube134_212"
                  rotation={[0, -Math.PI / 3, 0]}
                  scale={0.71}
                >
                  <mesh
                    name="Object_430"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_430.geometry}
                    material={materials.hide}
                  />
                </group>
                <group name="Cube136_213" rotation={[0, -0.87, 0]} scale={0.71}>
                  <mesh
                    name="Object_432"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_432.geometry}
                    material={materials.hide}
                  />
                </group>
                <group name="Cube138_214" rotation={[0, -0.7, 0]} scale={0.71}>
                  <mesh
                    name="Object_434"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_434.geometry}
                    material={materials.hide}
                  />
                </group>
                <group
                  name="Cube140_215"
                  rotation={[0, -Math.PI / 6, 0]}
                  scale={0.71}
                >
                  <mesh
                    name="Object_436"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_436.geometry}
                    material={materials.hide}
                  />
                </group>
                <group name="Cube142_216" rotation={[0, -0.35, 0]} scale={0.71}>
                  <mesh
                    name="Object_438"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_438.geometry}
                    material={materials.hide}
                  />
                </group>
                <group name="Cube144_217" rotation={[0, -0.17, 0]} scale={0.71}>
                  <mesh
                    name="Object_440"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_440.geometry}
                    material={materials.hide}
                  />
                </group>
                <group name="Cylinder001_218" scale={0.71}>
                  <mesh
                    name="Object_442"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_442.geometry}
                    material={materials.hide}
                  />
                </group>
                <mesh
                  name="Object_368"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_368.geometry}
                  material={materials.material_0}
                />
              </group>
              <group
                name="Sphere072_220"
                position={[0, -1.61, 0]}
                rotation={[-Math.PI, 0, 0]}
                scale={[1.32, 0.53, 1.32]}
              >
                <mesh
                  name="Object_444"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_444.geometry}
                  material={materials.ball}
                />
              </group>
              <group name="Plane_221" position={[0, -1.05, 0]} scale={2.35}>
                <mesh
                  name="Object_446"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_446.geometry}
                  material={materials.ball}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/spectral_circles.glb");
