/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Kai Christmann (https://sketchfab.com/kai_am_rhein)
license: CC-BY-NC-ND-4.0 (http://creativecommons.org/licenses/by-nc-nd/4.0/)
source: https://sketchfab.com/3d-models/toy-dino-allosaurus-b6617c83e9d64781b4b65081ce4c6fe1
title: Toy Dino Allosaurus
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import model from "./toy_dino_allosaurus.glb"
import { useFrame } from "@react-three/fiber";

export function ToyDinoAllosaurus(props) {
  const { nodes, materials } = useGLTF(model);
  let ref = useRef();

  useFrame(({clock}) => {
    ref.current.rotation.y += Math.sin(clock.getElapsedTime()) * 0.003;    
  })
  return (
    <group ref={ref} {...props} dispose={null} rotation={[0,-15*Math.PI/180,0]}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[Math.PI / 2, 0, 0]} scale={2}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_6.geometry}
              material={materials.material}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("toy_dino_allosaurus.glb");